name: Test with ESLint (non-master branch)
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  test:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - run: npm install
      - run: npx eslint .
