name: Test
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - run: . .github/workflows/fix-coverage-directories.sh
      - run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
